print('               ')
print('  HELLO WORLD  ')
print('  23571113171  ')
print('               ')
print('     *****     ')
print('    *******    ')
print('      *I*      ')
print('       I       ')
print('       A       ')
print('  -----------  ')
print('               ')
print('  HELLO  TREE  ')
print('               ')